Cargo.lock
Dockerfile
core/Cargo.toml
package.json

Resolves #21 
Naive and unoptimized approach for cross compilation during Docker build. Result is a multi-arch Docker image.
Cross compilation to aarch64 takes a while on my machine (~ 2hrs), but it works. amd64 version builds significantly faster (< 30mins).
Please be aware that you'll need to have buildx set up as described in [the Docker blog post for it](https://www.docker.com/blog/how-to-rapidly-build-multi-architecture-images-with-buildx/ ).
The conditional to skip non-targetarch build stages is described in [this blog post by Docker](https://www.docker.com/blog/advanced-dockerfiles-faster-builds-and-smaller-images-using-buildkit-and-multistage-builds/).

Enable cross compilation (Docker) to aarch64-unknown-linux-musl

---

.github/workflows/ci.yaml

This updates the existing build on push. The two jobs (one each for the Rust and TypeScript code) run in parallel, and both make use of caching to speed up their runs, as requested.
I explicitly use the TS type check commands in the two directories I see `tsconfig.json` files rather than running `pnpm run checks` at the top level, as that'd require the Rust setup in both jobs. That'd work, but I'd recommend collapsing the two jobs into one and forgoing the concurrency in favor of command simplicity.
Fixes #68
re: https://github.com/aaronleopold/stump/pull/71

Update GHA CI build

---

stump.service

Signed-off-by: Lars Erhardt <lars@krautbyte.com>
Added a small and simple SystemD Service file that people might use to run Stump as a Service.

Added SystemD Service File

---

apps/server/src/routers/api/user.rs

- User password or name or both can be updated by id
- get user by id
- admin can delete user by id but user cannot for now

user api functions

---

scripts/release/Dockerfile
scripts/release/entrypoint.sh

This change implements an entrypoint-script for the docker container.
By passing environment variables `PUID=<numeric user id>` and `PGID=<numeric group id>` to the container, which is started as root by the docker daemon, can downgrade to the respective user and run the stump server daemon with lower privileges.
This also ensures that mounted directories/volumes are assigned and accessed with proper permissions.
**NOTE**: This essentially breaks the invocation via `--user` argument, currently documented on [Docker hub](https://hub.docker.com/r/aaronleopold/stump-preview)
- Fixes issue #56
Example docker compose
```yaml
version: '3.3'
services:
stump:
image: aaronleopold/stump-preview:latest
container_name: stump
volumes:
- /home/user/.stump-config:/config
- /media/books:/data
ports:
- …
```

docker: Allowing to downgrade to regular user via environment variables

---

core/src/fs/scanner/batch_scanner.rs
core/src/job/jobs.rs

I am introducing a concurrency limit for the batch scan, something that definitely should have previously been in place. Rather than spawning threads for each series, no additional threads are spawned (except in the file count calculation, but that will be tacked later down the road). The `scan_series` futures are streamed and ran in parallel up to 10 at a time. I'm hopeful this alone will help with some of the memory issues for massive libraries, outlined in https://github.com/aaronleopold/stump/issues/102.

fix(maybe lol): limit concurrency

---

packages/client/src/queries/filesystem.ts
packages/interface/src/components/DirectoryPickerModal.tsx
packages/interface/src/scenes/library/explorer/FileExplorerNavigation.tsx
packages/interface/src/scenes/library/explorer/LibraryExplorerScene.tsx

Fixes #142 
I don't want to spend much more time on the file explorer for now, since I'd rather dedicate time elsewhere, *but* I went ahead an made a few additional tweaks with small improvements to the backwards/forward navigation. I also added an optional prop to enforce a 'minimum directory' via `enforcedRoot` (but I kinda hate the name)

fix: explorer shows wrong path on refresh

---

Cargo.lock
Cargo.toml
core/src/lib.rs

Fixes https://github.com/stumpapp/stump/issues/146, though to be honest I'm not sure why the issue randomly started cropping up to begin with. I tracked down the issue being a change introduced in https://github.com/stumpapp/stump/pull/141. I started with the `schema.prisma` changes and the problem presented immediately once I added those in. There have been multiple passing docker builds since this PR, which is why it is so puzzling that this fix is now all of the sudden needed. 
The musl version in the docker images I use did change a week ago from `1.1.24` to `1.2.3`, which seems to correspond to the last successful PR run, but I'll have to look into whether that is a potential cause another time.
I updated prisma while I was at it

bug: fix recursion error during docker compilations

---

.github/actions/setup-cargo/action.yml
Cargo.lock
Cargo.toml
core/Cargo.toml
core/src/filesystem/media/common.rs
core/src/filesystem/media/rar.rs
core/src/filesystem/media/zip.rs
packages/client/src/hooks/useCoreEvent.ts
packages/client/src/invalidate.ts

Archives with alphanumeric filenames internally should now be sorted properly when served
- Added `alphanumeric-sort` and created simple wrapper function
- Upgrade `prisma-client-rust` and `prisma-client-rust-cli`. Hopefully no issues in CI relating to this, so I can move off of my fork

bug(core): fix alphanumeric sorting

---

packages/interface/src/components/readers/epub/controls/TocDrawer.tsx

There was a bad effect that prematurely closed the TOC drawer, I basically just used the wrong hook. This should fix the bug, but this component in general needs lots of TLC and a better design

:bug: fix autoclosing drawer

---

scripts/release/entrypoint.sh

Fixes https://github.com/stumpapp/stump/issues/159
`entrypoint.sh` had a few commands that needed adjustment, and then an additional workaround for when the provided `PUID` is already mapped to an existing user.

:bug: Fix entrypoint.sh adduser and addgroup commands

---

packages/interface/src/components/readers/epub/EpubJsReader.tsx
packages/interface/src/scenes/book/BookReaderScene.tsx

This pull request is a response to issue #123, which requested the left/right arrow keys be usable for previous/next page navigation when reading books.
I implemented this with a new effect in BookReaderScene.tsx which adds a keydown listener and navigates on `ArrowLeft` and `ArrowLeft` if the current page isn't the first/last page.
Happy to make any changes needed, I'm less familiar with React so I may not have done this the ideal way.

feat: add support for arrow key navigation

---

crates/cli/src/commands/account.rs
crates/cli/src/lib.rs
packages/interface/src/AppRouter.tsx
packages/interface/src/components/ApplicationVersion.tsx

The migration from https://github.com/stumpapp/stump/pull/186 causes the server owner status to not be reassigned after removing the old representation, so you'd have no server owner afterwards. To remedy this, I've added a new CLI command to assign a user the server owner status:
```bash
./stump account reset-owner
```
If you have direct database access you can of course just flip the boolean value of `is_server_owner` manually

🐛 Fix no server owner after migration

---

apps/server/src/config/session/mod.rs
apps/server/src/config/session/utils.rs
apps/server/src/http_server.rs
apps/server/src/middleware/auth.rs

Extend the session service error handler with a proper response that will set the appropriate headers to encourage the client to remove Stump cookies

:bug: Attempt to unset invalid or otherwise bad cookies

---

apps/desktop/moon.yml
apps/web/moon.yml
docs/moon.yml
package.json
packages/components/moon.yml
packages/interface/src/components/readers/image-based/PagedReader.tsx
pnpm-lock.yaml

🐛 Fix hotkey bug in image reader

---

apps/server/src/routers/api/mod.rs
apps/server/src/routers/api/v1/media.rs
apps/server/src/routers/api/v1/series.rs
apps/server/src/routers/utoipa.rs
packages/api/src/media.ts
packages/client/src/queries/media.ts
packages/client/src/queries/series.ts
packages/interface/src/scenes/book/BookCompletionToggleButton.tsx
packages/interface/src/scenes/book/BookOverviewScene.tsx
packages/interface/src/scenes/book/BookReaderLink.tsx
packages/interface/src/scenes/book/BookReaderScene.tsx
packages/interface/src/scenes/book/management/BookThumbnailSelector.tsx
packages/interface/src/scenes/series/management/SeriesThumbnailSelector.tsx
packages/interface/src/utils/patterns.ts
packages/types/generated.ts

Resolves https://github.com/stumpapp/stump/issues/206
Resolves https://github.com/stumpapp/stump/issues/204

✨ Book completed toggle button and fix read again button

---

core/src/db/client.rs

Replaced with `_query_raw` and an explicitly typed response struct

🐛 Invalid query method for setting journal_mode 

---

.vscode/settings.json
Cargo.lock
Cargo.toml
apps/server/Cargo.toml
apps/server/src/main.rs
core/Cargo.toml
crates/cli/Cargo.toml
crates/cli/src/commands/account.rs
crates/integrations/Cargo.toml

* Update workspace dependencies and added async-trait as a workspace dependency.
* Update all rust dependencies to latest non-breaking version.
* Update settings.json because "source.fixAll.eslint" setting was changed to a string value.
* Change `debug_setup` in server main.rs to be annotated with `cfg(debug_assertions)`.
* Address todos in CLI crate, adding prettytable-rs as a dependency.

🎨 General housekeeping

---

interface/src/components/readers/epub/themes.ts

Fixes https://github.com/stumpapp/stump/issues/243
Note that I only had access to one of the files from the linked issue, I added an explicit color to the `body` that will hopefully catch any other missed elements

🐛 Fix ul text color in EPUB reader

---

interface/src/AppRouter.tsx

Accidentally left the conditional rendering on the last PR, this removes it so you can access the smart list pages

:bug: Render `SmartListRouter` outside of development

---

Cargo.lock
Cargo.toml
core/Cargo.toml
core/src/filesystem/media/rar.rs
docker/Dockerfile

PR fixes an issue that caused `unrar` to error when encountering unicode characters in the file name
- Pull in `libc` as Linux-only dep
- Explicitly set the locale before interacting with RAR files (when OS is Linux)

🐛 Fix opening RAR files with unicode characters

---

apps/server/src/lib.rs
apps/server/src/middleware/auth.rs
core/src/context.rs

Several doctests were failing and I got them passing.

:white_check_mark: Update failing tests

---

apps/server/src/routers/api/v1/media.rs
packages/browser/src/components/Pagination.tsx
packages/browser/src/components/media/BookSearch.tsx
packages/browser/src/components/navigation/mobile/MobileTopBar.tsx
packages/browser/src/scenes/home/HomeScene.tsx
packages/browser/src/scenes/library/LibraryBooksScene.tsx
packages/browser/src/scenes/library/LibrarySeriesScene.tsx
packages/browser/src/scenes/series/SeriesBooksScene.tsx
packages/client/src/queries/index.ts
packages/client/src/queries/media.ts
packages/client/src/queries/series.ts
packages/components/src/progress/ProgressBar.tsx

A PR for various bug fixes and improvements while testing `develop` in preparation for `0.0.2`. I'll keep the git history clean to make the changelog more explicit in what's been fixed.

0.0.2 bug hunting

---

packages/browser/package.json
packages/components/package.json
yarn.lock

:arrow_down: Downgrade `react-hook-form` to `7.47.0` (#316)

---

packages/browser/src/components/readers/epub/EpubReaderHeader.tsx
packages/browser/src/components/readers/epub/controls/EpubNavigationControls.tsx
packages/browser/src/scenes/book/EpubReaderScene.tsx

Fixes #323
I accidentally inverted the swipe handlers, e.g. assigning `onLeftNavigate` to `onSwipedLeft`. Semantically, this is a mess. I'm being a bit pedantic, but I did not land on variable names I like lol I just added comments to hopefully prevent the mix up again.
Also noticed the header action items on mobile are rather small, so I made a [note to gather feedback](https://github.com/stumpapp/stump/commit/afa00c03b60a022dfb905271d8bdadcc0b992aaf#diff-3333bd75c34b2849159b045890e068e9e7bbd84bf64f6f57f0e642724ed2b427R17-R18). If anyone has thoughts, please reach out.

:bug: Fix inverted swipe handlers in EPUB reader

---

packages/browser/src/scenes/book-club/home/BookClubNavigation.tsx
packages/browser/src/scenes/library/LibraryNavigation.tsx
packages/browser/src/scenes/series/SeriesNavigation.tsx

Backport the main stylistic fix from https://github.com/stumpapp/stump/pull/322. This does not include some of the small improvements to the light mode, though, just the small fix.

:adhesive_bandage: Fix dark styles in light theme

---

packages/browser/src/components/readers/image-based/PagedReader.tsx
packages/browser/src/hooks/index.ts
packages/browser/src/hooks/useDetectZoom.ts
packages/browser/src/scenes/book-club/home/BookClubNavigation.tsx
packages/browser/src/scenes/library/LibraryNavigation.tsx
packages/browser/src/scenes/series/SeriesNavigation.tsx

Resolves (hopefully) #328
I've adjusted the reader to be more programmatic and less CSS-centric for computing the navigation tap boundaries:
- If the loaded image is >= 80% of the width of the viewport, the navigation divs will be fixed to the left/right with a fixed 10% width
- If the loaded image is < 80%, the navigation divs will be inline left/right to the image and fill any available space
I've also added swipe handlers on mobile viewport sizes. I tested this on an iPad mini, and then a few other tablet sizes in my dev tools.

:bug: Fix image reader navigation (tablet)

---

core/prisma/migrations/20240428193209_bigint_media_size/migration.sql
core/prisma/schema.prisma
core/src/db/entity/media/entity.rs
core/src/filesystem/media/builder.rs
packages/browser/src/components/media/MediaCard.tsx
packages/browser/src/scenes/book/BookFileInformation.tsx
packages/types/generated.ts

Files which are >2.35 GB do not fit within `i32`, which is used for the `size` field on `media`. I have added a migration to store media size as an `i64`, so unless you have a file which is ~9223372036.85 GB you should be good lol

:bug: Fix cast error for file size calculation

---

Cargo.lock
core/Cargo.toml
core/src/config/stump_config.rs
crates/integrations/src/notifier/discord_client.rs
crates/integrations/src/notifier/telegram_client.rs

So I was investigating the failing tests as mentioned in the Discord earlier and I happened on a solution that seems sensible.
The crate [temp-env](https://crates.io/crates/temp-env) provides a way to set environment variables, run a test, then unset those variables. Embedding the tests involving environment variables in this crate's wrapper both makes it more ergonomic and also fixes the inconsistent passing of tests that I was experiencing (I interpret this as confirming that the previous tests were causing some sort of race condition where the environment variables for each were fighting each other).
Also, I set the telegram and discord tests to be ignored since they rely on local variables being set. It's probably a good idea to fix those in the future, but this will also open the way …

:white_check_mark: Fix stump_config tests

---

apps/server/src/middleware/auth.rs
apps/server/src/routers/api/v1/auth.rs
apps/server/src/routers/mod.rs

Relates to https://github.com/stumpapp/stump/issues/346
The recent change to split the main OPDS router into sub-routers for each supported version caused some issues in the auth middleware. Specifically, the `/opds` prefix was missing which caused the conditional check which allows basic auth for OPDS-specific routes to fail.
Accessing the request parts `uri` in an extension seems to be scoped to the current router. This means when the auth middleware attempted to extract the `uri`, it was now relative to the new sub-router (which in this case, would be /v1.2/*). To correct this, I just used the `OriginalUri` extractor.
I also used this as an opportunity to fix some of the session handling logic in the OPDS auth flow

:bug: Fix OPDS path detection regression

---

apps/web/src/App.tsx
packages/client/src/queries/auth.ts
packages/types/index.ts

Fixes #356
- Replace `window.location.href` with `window.location.origin` when initializing the base URL for the API
- Basic type enforcement for invalid `me` query response
The root cause seems to be that, when in an unauthenticated state, the initial visit to a non-root route would initialize the API URL incorrectly to include the pathname. This was a quick lunch fix, so I'll merge it either after work today or tomorrow

:bug: Fix first visit API URL determination

---

packages/browser/src/components/readers/epub/EpubJsReader.tsx

Fixes #357
This is a bit of a cheeky solution, but it seems to work 🤷. I've basically manually focused on the EPUB.js iframe whenever the location changes. This isn't inefficient per se, but I'll see if I can find and fix the actual, underlying issue over the weekend

:bug: Focus EPUB.js iframe each location change

---

.github/codecov.yml
.github/workflows/ci.yaml
.vscode/settings.json

This is a redo of a previous pull request attempt that failed because I made it from a fork (#364). I have since closed the pull request, but its text is reproduced below:
> This is a very simple pull request that adds CodeCov-based automated code coverage tracking. It will require some repository owner intervention to get fully functional.
>
> I've added an action that runs [cargo-llvm-cov](https://github.com/taiki-e/cargo-llvm-cov). This runs all tests in release mode and generates lcov.info, which contains coverage data (NB: if you're using a coverage tracking extension then you can use visualize this file in your IDE, very helpful for designing tests).
>
> The next action uploads this data to [codecov.io](https://about.codecov.io/), which offers free code coverage hosting for open …

👷 Add code coverage tracking

---

core/src/config/mod.rs
core/src/db/entity/emailer/entity.rs
core/src/db/entity/notifier.rs
core/src/filesystem/archive.rs
core/src/filesystem/common.rs
core/src/utils.rs

This pull request adds additional tests to the core crate. So far I have added:
- utils tests
- filesystem/common tests
- filesystem/archive tests

✅ Add core tests to improve coverage

---

.github/actions/build-server/action.yml
.github/actions/build-web/action.yml
.github/actions/setup-rust/action.yml
.github/actions/upload-artifact/action.yml
.github/workflows/release_binary.yml

This pull request adds a new workflow to build and release a binary package of the Stump server, so that users can directly run the server rather than using a Docker container. It aims to close #310 once complete.
The workflow is intended to be manually triggered, with the desired version number/tag for the release being input at that time. For example, the user could trigger the workflow with `version = 1.0.0` and the result would be a draft release called "Release 1.0.0" tagged "v1.0.0."

👷 Release server binary

---

docs/pages/installation/docker.mdx

Current `docker compose` file standard no longer uses the `version` element and having it throws a warning.
```
WARN[0000] ./stump/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
```
https://docs.docker.com/compose/compose-file/04-version-and-name/
Updated the example in the docs to remove `version`.
\* let me know if you want an issue opened as well, but this seemed tiny.

:hammer: Update docker-compose file example in docs to remove version

---

apps/server/src/routers/api/mod.rs
apps/server/src/utils/auth.rs
core/src/filesystem/media/builder.rs

Fix issue where passwords containing `:` character break Basic Auth used on API endpoints (particularly OPDS).

:bug: Fix basic auth password parsing breaking on : character

---

core/src/filesystem/content_type.rs

Quick fix of a typo I noticed while looking at logs (`infered` -> `inferred`). Doesn't appear anywhere else, just this one place.

:pencil2: Fix infered typo

---

core/src/filesystem/image/webp.rs

This pull request reverts some changes made in #351 which inadvertently caused generating Webp thumbnails to fail.
The problem, as identified in the Discord by @fehwalker, was caused by changes to `WebpProcessor::generate` which assumed that the input data was formatted as webp, meaning that attempts to convert non-webp images into webp would fail.
I've retained my changes to `WebpProcessor::generate_from_path` because they allow tests to pass that, in my view, should pass. In any event, this function is not called within Stump at any point, so it is likely irrelevant.

🐛 Fix bug in `WebpProcessor::generate`

---

.github/actions/build-server/action.yml
.github/workflows/ci.yaml
.github/workflows/experimental.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/release_binary.yml

This builds off of the work from #369 to close #310
I'll try to test it during the week with some debug commits to trigger the workflow before merging this in

:construction_worker: Add `macOS` platform to binary release workflow

---

apps/server/src/routers/api/v1/user.rs
core/src/db/entity/user/permissions.rs

Fixes an issue discussed on Discord: https://discord.com/channels/972593831172272148/972595078554079232/1271953758326227065

:bug: Fix 422 error relating to invalid user permission

---

.github/workflows/experimental.yml
.github/workflows/nightly.yml

I noticed that while the path filters work as expected for PR events, once merged the base which it uses to diff against is main, which means there will almost always be code-related changes and so the builds don't get skipped. By specifying the base, I'm hoping this gets fixed. The docs state this arg is ignored for PR events, so should have no effect there

:adhesive_bandage: Fix path filter on push

---

.github/workflows/ci.yaml

This small change will run the CI when a change is made to `develop` (in addition to `main`) and should make it easier to track improvements in coverage over time.

👷 Run ci on pushes to develop

---

apps/server/src/routers/api/v1/library.rs
packages/browser/src/scenes/book/BookOverviewScene.tsx

This was missed before the historical read history feature was merged, the SQL referenced a now non-existent table

:bug: Fix invalid SQL for library stats query

---

.github/actions/build-docker/action.yml
.github/workflows/ci.yaml
.github/workflows/experimental.yml
.github/workflows/nightly.yml

Set the `runs-on` to target my self-hosted runner

:green_heart: Fix `runs-on` for docker build workflows

---

docker/Dockerfile
docker/entrypoint.sh

Adding explicit linking to the process appears to fix the error that I was experiencing in Docker builds that I mentioned in [#406](https://github.com/stumpapp/stump/issues/406#issuecomment-2299452296):
```
stump  | /app/stump: error while loading shared libraries: libdav1d.so.7: cannot open shared object file: No such file or directory
stump exited with code 0
```
The Dockerfile still does not build locally despite adding a step to generate `prisma.rs` because of this error but that seems to be a separate issue:
```
^^^^^^^^^^^^ help: a static with a similar name exists: `DATAMODEL_STR`
175.6
175.6 error[E0425]: cannot find value `MIGRATIONS_DIR` in module `super`
175.6  --> core/src/prisma.rs:3:3446816
175.6   |
175.6 3 | ...igrate_deploy (super :: DATAMODEL_STR , super :: …
```

🔨 Fix docker `dav1d` shared library linking 

---

docs/components/DownloadLinks.tsx
docs/components/Footer.tsx
docs/components/Hero.tsx
docs/package.json
yarn.lock

See https://github.com/simple-icons/simple-icons/issues/11236
This PR pins the dependency as an immediate and temporary fix. The full fix will be to remove the pin and manually get the Microsoft approved icons to use

:pushpin: Pin `@icons-pack/react-simple-icons` to `9.1.0`

---

apps/expo/src/components/book/BookListItem.tsx
packages/browser/src/components/book/BookCard.tsx
packages/browser/src/scenes/book/BookOverviewScene.tsx
packages/browser/src/scenes/book/DownloadMediaButton.tsx

The filename was being displayed instead of prioritizing the `title` from metadata (if present)

:bug: Fix book titles in entity cards

---

apps/server/src/routers/api/v1/media.rs
apps/server/src/routers/opds/v1_2.rs

Fixes an issue where generated thumbnails aren't actually being loaded, rather the file is being opened. I also made a note for two items:
- Improve a silly query
- Support `STRICT_OPDS` configuration, which will convert any non-compliant OPDS images, rather than just always doing it
I will tackle both alongside the image serving work I plan to do this weekend
See [Discord](https://discord.com/channels/972593831172272148/972595055061794856/1276284767133896856) for additional context

:bug: Fix OPDS thumbnail endpoint

---

core/src/filesystem/common.rs
core/src/filesystem/content_type.rs
core/src/filesystem/image/process.rs

Minimal changes to allow for AVIF files to be served to browser (I believe almost all browsers support [AVIF](https://caniuse.com/avif) at this point).

:sparkles: Avif file serving support

---

core/src/db/entity/library/entity.rs
core/src/db/entity/library/mod.rs
core/src/db/entity/library/prisma_macros.rs
core/src/db/entity/mod.rs
core/src/filesystem/scanner/library_scan_job.rs
core/src/filesystem/scanner/series_scan_job.rs
core/src/filesystem/scanner/walk.rs

A cherry-pick of https://github.com/stumpapp/stump/pull/422/commits/61e7dbdd03b296bae40340a379c0b476a238c4fc which contains a fix for root-level series scanning (i.e. the library itself is a series)

:bug: Fix regression in scanner for root-level series

---

.github/actions/build-docker/action.yml
.github/workflows/nightly.yml
docker/build.sh

lol so I forgot to add `--push` when publishing the builds 🙃

:green_heart: Fix docker build push

---

.github/actions/build-docker/action.yml
core/src/filesystem/scanner/library_scan_job.rs
core/src/filesystem/scanner/series_scan_job.rs

Fixes a bug introduced from the fix which aimed to correct a regression in the scanner lol https://github.com/stumpapp/stump/pull/423
The crux of the issue is outlined in the code to (hopefully) prevent a similar bug from slipping through the cracks again: 
```
If the library is collection-priority, any child directories are 'ignored' and their files are part of / folded into the top-most folder (series).
If the library is not collection-priority, each subdirectory is its own series.
Therefore, we only scan one level deep when walking a series whose library is not collection-priority to avoid scanning duplicates which are part of other series
```

:bug: Fix max-depth for collection-priority libraries

---

Cargo.lock
Cargo.toml
apps/server/Cargo.toml
core/Cargo.toml
core/src/filesystem/error.rs
core/src/filesystem/media/pdf.rs
crates/cli/Cargo.toml

This pull request updates a few of the dependencies to their latest version, just a little housekeeping.
The only substantive change is that the `pdfium_render` crate's latest version changed its interface so that you now have to import everything from the prelude module, e.g.,: `use pdfium_render::prelude::{PdfRenderConfig, Pdfium}`. Weird choice imo.

⬆️ Update dependencies

---

Cargo.lock
core/Cargo.toml
core/src/filesystem/archive.rs

Relates to #427
This should greatly improve performance of IO-operations on ZIP files and improve a growing memory issue. For full context, see https://github.com/stumpapp/stump/issues/427#issuecomment-2332857700

:arrow_down: Downgrade `zip` crate to `1.1.3`

---

docker/Dockerfile

The updates from https://github.com/stumpapp/stump/pull/433 required updating the PDFium library, but that was missed. This PR updates to the latest `chromium/6707`
See https://discord.com/channels/972593831172272148/1283431932830547979 for more context

:arrow_up: Update bundled `PDFium` version in Docker

---

apps/server/src/config/session/mod.rs
apps/server/src/config/session/utils.rs
apps/server/src/errors.rs
apps/server/src/middleware/auth.rs
apps/server/src/routers/api/v1/media.rs
apps/server/src/routers/opds/v2_0.rs

This PR contains two (and potentially 3) fixes relating to using the experimental OPDS V2 with Cantook on Android:
1. The `id` field in the auth document is now the full service URL, not the relative path. This caused an immediate crash on Android for whatever reason
2. The route handler which serves the auth document is now excluded from any auth guard. I am personally not a huge fan of this, as I like to minimize the surface of unauthenticated endpoints. However, there seems to be no other way around it
3. Instances of `APIError` (and a few other OPDS-specific 401 responses) will attempt to instruct the client to remove any cookies. The former _used_ to exist, however seems to have been accidentally removed as of https://github.com/stumpapp/stump/pull/400
I want to note that none of …

:bug: Fix Cantook crash on Android

---

packages/browser/src/paths.ts
packages/browser/src/scenes/settings/app/general/ProfileForm.tsx
packages/browser/src/scenes/settings/server/users/create-or-update/AccountDetails.tsx
packages/browser/src/scenes/settings/server/users/create-or-update/CreateOrUpdateUserForm.tsx
packages/browser/src/scenes/settings/server/users/create-or-update/MaxSessionsAllowed.tsx
packages/browser/src/scenes/settings/server/users/create-or-update/UserPermissionsForm.tsx
packages/browser/src/scenes/settings/server/users/create-or-update/UserRestrictionsForm.tsx
packages/browser/src/scenes/settings/server/users/create-or-update/__tests__/AccountDetails.test.tsx
packages/browser/src/scenes/settings/server/users/create-or-update/__tests__/MaxSessionsAllowed.test.tsx
packages/browser/src/scenes/settings/server/users/create-or-update/__tests__/UserPermissionsForm.test.tsx
packages/browser/src/scenes/settings/server/users/create-or-update/__tests__/UserRestrictionsForm.test.tsx
packages/browser/src/scenes/settings/server/users/create-or-update/__tests__/schema.test.ts
packages/browser/src/scenes/settings/server/users/create-or-update/schema.ts
packages/browser/src/scenes/smartList/create-or-update/form/schema.ts
packages/browser/src/scenes/smartList/settings/UserSmartListSettingsScene.tsx
packages/components/src/button/Button.tsx
packages/i18n/src/locales/en.json

This PR fixes a recent regression in nightly causing the submit button for the create/update user form to not submit the form. This doesn't affect the latest build
I took this as an opportunity to refactor some of the code in that section, primarily using `useFormState` where necessary, and added a suite of tests to assert basic behavior

:bug: Fix create user form submit

---

.github/workflows/ci.yaml
apps/server/src/routers/api/v1/library.rs
apps/server/src/routers/api/v1/media.rs
apps/server/src/routers/api/v1/series.rs
apps/server/src/routers/api/v1/user.rs
apps/server/src/utils/upload.rs
core/src/config/stump_config.rs
core/src/job/worker.rs

As I was reading through the code while preparing to eventually handle the file upload/deletion/bulk management features, I happened on some code for uploading images with a todo marked asking to eventually add configurable max size.
That was easy enough, so I added it as a configuration variable with a default value equal to the prior 20 MB hard-coded limit. I also took the opportunity to refactor the code in the `upload` module so that it can be more easily reused when other upload types are added.

♻️ Refactor upload image and add max_size

---

core/src/filesystem/media/process.rs

Fixes a bug where PDF books would cause the catalog to error with unsupported format

:bug: Fix PDF books in OPDS V2 catalog

---

.github/workflows/release_docker.yml

It was brought to my attention that my version of buildah causes issues with rootless docker. Until I can update both runners to be at a version where the issue doesn't present, the release workflow will have to be set to only run on the larger runner

:green_heart: Fix latest builds for rootless docker

---

core/src/job/worker.rs
core/src/lib.rs

Should fix the following: https://github.com/stumpapp/stump/actions/runs/11138014373/job/30952354385

:rotating_light: Fix fmt after rust upgrade

---

core/src/db/filter/smart_filter.rs
packages/browser/src/components/smartList/createOrUpdate/__tests__/schema.test.ts
packages/browser/src/components/smartList/createOrUpdate/queryBuilder/filterGroup/FieldSelector.tsx
packages/browser/src/components/smartList/createOrUpdate/queryBuilder/filterGroup/OperatorSelect.tsx
packages/browser/src/components/smartList/createOrUpdate/schema.ts
packages/browser/src/components/smartList/createOrUpdate/sections/FilterConfigJSON.tsx
packages/components/src/select/ComboBox.tsx
packages/i18n/src/locales/en.json
packages/sdk/src/types/generated.ts

I've added UI hookups for filtering on series metadata, as requested on Discord
@JMicheli The macro is 🔥

:sparkles: Extend smartlist filters for series metadata

---

packages/browser/src/components/explorer/FileExplorerProvider.tsx
packages/browser/src/components/explorer/grid/FileGridItem.tsx

I noticed an issue in the `FileExplorer` component that seems to have followed on the sdk overhaul. The function `getBook` defined here requires an `sdk: Api` parameter:
https://github.com/stumpapp/stump/blob/2409a6e04371af8ba2421154da96a0588ff1811a/packages/browser/src/components/explorer/FileThumbnail.tsx#L112-L134
However, a few calls to `getBook` didn't include the parameter, which caused them to fail. As a result, when double clicking a file in the explorer, you'd get this response:
The changes I made seem to fix it, but it would be good to have review by someone more familiar with React to make sure that any other changes that I may have missed are made.

🐛 Fix bug in `FileExplorer` that broke clicking on books.

---

core/src/error.rs
core/src/job/error.rs
core/src/opds/v2_0/error.rs
crates/cli/src/error.rs

The new version of rust comes with a new clippy lint that triggers on enums with large sizes. Enums have a size equal to their largest contained variant.
The `CoreError` enum came in at 144 bytes as the result of containing `prisma_client_rust::QueryError`, which is huge. This is easily fixed by boxing the type, which shut clippy up.
There are some other big variants still, but nothing over 100 bytes.

:rotating_light: Wrap large enum variants in `Box`

---

apps/server/src/config/session/utils.rs
apps/server/src/routers/api/v1/auth.rs
packages/browser/src/components/navigation/sidebar/Logout.tsx
packages/browser/src/components/navigation/sidebar/SignOut.tsx
packages/browser/src/scenes/auth/LoginOrClaimScene.tsx

This PR should fix a bit of an annoying bug which caused an overload of history pushes after login in a *very* specific scenario. At first, I thought this was just a quirk of having 3-4 testing instances of Stump with competing cookies causing flakes. The issue seemed to present when you manually log out and try to re-auth immediately.
The actual cause was that the query cache for fetching the logged in user did not clear correctly after logout. A logout triggered a refetch, which returned a 401. When you re-logged in (without a full browser refresh) that 401 remained the non-stale result so you immediately would get smacked back into auth, and then back, and then back again, etc.
The fix was really a mix of a few things:
- Update the delete cookie response for 401 API errors to have …

:bug: Fix auth redirect issue after logout

---

packages/browser/src/components/readers/imageBased/paged/PageSet.tsx
packages/browser/src/components/readers/imageBased/paged/PagedReader.tsx

- The first page is the cover, so it should be shown by itself instead of in double spread (maybe this could be optional)
- requires skip variable to make it possible to go back to page 1 (else it will try to subtract two pages from page 2)
- Reading right to left vs left to right requires flipping the ordering of the pages
(never coded a line of javascript before tonight, so sorry if it the code is awful...)

:bug: Exclude cover image from double spread and fix rtl

---

core/src/filesystem/scanner/library_scan_job.rs
core/src/filesystem/scanner/series_scan_job.rs

Fixes an issue in collection-priority libraries where having a root-level book causes the scanner to create a series with the entire content of the library, effectively duplicating all books in the database.
This is a simple change to just make the scanner aware of this scenario and adjust the indexing depth accordingly.

:bug: Fix root-level books in collection libraries

---

.github/workflows/nightly.yml
Cargo.lock

It seems that `arrayvec` is not pulling correctly for `arm` in the Docker build. I'm hoping this manual update fixes the issue. 
See https://github.com/stumpapp/stump/actions/runs/11603151339/job/32310833324#step:4:886

:arrow_up: Update `arrayvec` transient dependency

---

apps/server/src/errors.rs
apps/server/src/routers/api/mod.rs

This pull request just does a couple of things:
1. It boxes the `QueryError` in `APIError`, which silences a clippy warning.
2. It walks back the silly each-item-individually change I made in routers::api::v1 for exported values. That was messy.

🎨 Server housekeeping

---

core/src/config/stump_config.rs
docs/components/InlineIcon.tsx
docs/pages/faq.md
docs/pages/guides/_meta.ts
docs/pages/guides/access-control/age-restrictions.mdx
docs/pages/guides/basics/books.md
docs/pages/guides/basics/libraries.mdx
docs/pages/guides/basics/series.mdx
docs/pages/guides/basics/thumbnails.mdx
docs/pages/guides/configuration/server-options.md
docs/pages/guides/configuration/theming.md
docs/pages/guides/index.md
docs/pages/guides/mobile/app.mdx
docs/pages/guides/upload.mdx
docs/pages/installation/executable.mdx
packages/browser/src/components/explorer/upload/UploadModal.tsx

I figured we should begin drafting documentation for the upload feature so that when it eventually makes its way down the pipeline there will be something to guide users through enabling it and understanding how to configure and use it.
I'm marking this as a draft to ensure that it meets the style and content expectations for the project.

📝 Document upload functionality

---

packages/browser/src/components/UserMenu.tsx
packages/browser/src/components/navigation/sidebar/SideBar.tsx
packages/browser/src/components/navigation/sidebar/sections/library/LibraryOptionsMenu.tsx
packages/browser/src/scenes/library/tabs/settings/LibrarySettingsHeader.tsx
packages/components/src/dropdown/DropdownMenu.tsx

I noticed my [previous PR](https://github.com/stumpapp/stump/pull/497) introduced an issue on mobile viewports 😱  :
https://github.com/user-attachments/assets/f9b7beac-308b-4267-a198-adf98f70b65b
This PR fixes the issue! I took some time to look at the other uses of `<DropdownMenu/>` to make sure they work as expected in mobile and desktop viewports. Also fixed UserMenu's Popover which was having the same issue as shown above.
https://github.com/user-attachments/assets/763dbf6c-a72d-442c-9a50-e23a759d77fa
------
Separately, I noticed some small UI issues that only happened if the viewport was exactly `768px` so I took care of those as well:
- missing header and footer in sidebar
- library settings header padding offset 
<details><summary>Screenshots</summary>
<p>
</p>
</details>

🐛 Fix popover and dropdown on mobile sidebar

---

apps/web/src/index.html

Is this something we're interested in? Any concerns or improvements? we could support more themes if needed!
https://github.com/user-attachments/assets/d90c7fa3-8044-444b-8386-7e67652e314a

💄 Add splash animation within web index file

---

.github/workflows/nightly.yml
apps/server/src/routers/opds/v1_2.rs

Fixes #513
This was a classic instance of organizing the router layers incorrectly, so the API key middleware was being run for both variants of the router instead of just when the `:api-key` path hits a match.
This is a pretty large bug that somehow went missed for the 3-4 weeks this sat in the nightly image lol I'll release `0.0.9` as a hotfix ideally tomorrow

:bug: Fix Path extractor error in v1.2 OPDS router

---

.github/workflows/nightly.yml
apps/server/src/middleware/auth.rs
apps/server/src/routers/opds/v1_2.rs
core/src/opds/v1_2/entry.rs
core/src/opds/v1_2/feed.rs

Fixes #516
The feed generation logic was missing some key changes to properly route users to the correct location when using API keys in the OPDS v1.2 feed. The logic had to be made a bit more dynamic to account for the two scenarios:
1. No API key
2. API key

🐛 Fix API key OPDS links in v1.2 feed

---

.github/CHANGELOG.md
Cargo.lock
Cargo.toml
apps/desktop/package.json
apps/expo/package.json
apps/server/src/middleware/auth.rs
apps/server/src/routers/opds/v1_2.rs
apps/web/package.json
core/src/opds/v1_2/entry.rs
core/src/opds/v1_2/feed.rs
package.json
packages/browser/package.json
packages/client/package.json
packages/components/package.json
packages/i18n/package.json
packages/sdk/package.json

This is a small patch release to fix a critical regression that broke v1.2 OPDS:
Fixes https://github.com/stumpapp/stump/issues/513
Fixes https://github.com/stumpapp/stump/issues/516

🔖 Release v0.0.9

---

core/src/db/entity/epub.rs
packages/browser/src/components/readers/epub/locations/TableOfContents.tsx
packages/sdk/src/types/generated.ts

Some epub content items have more content items inside! This PR exposes them to the reader.
First time working with Rust 😅 - criticism welcome!

✨ render children of an epub content item

---

apps/server/src/routers/api/v1/media/individual.rs
apps/server/src/routers/api/v1/media/mod.rs
core/src/db/entity/media/prisma_macros.rs
core/src/db/entity/metadata/prisma_macros.rs
packages/sdk/src/controllers/media-api.ts

This was asked on Discord to allow for better scripting capabilities when using the SDK
Note that PUT'ing the metadata requires `library:manage` permission

✨ Add GET and PUT endpoints for media metadata

---

apps/server/src/config/cors.rs

This pull request addresses the problem raised in #537, which causes Stump to fail to start when a wildcard ("*") is used in the allowed origins configuration variable.
The cause is that Axum doesn't like wildcards being added via the `AllowOrigin::list()` function and wants you to use `AllowOrigin::any()` instead. I slightly reorganized the server's `get_cors_layer()` function to detect when a "*" is present in the list of allowed origins and exit early with an `AllowOrigin::any()` configuration. 
I'm making the assumption is that there is no case where the allowed origin list would include a wildcard and then other origins but the user would expect behavior other than any origin being allowed. I think that's right.

🐛 Change CORS layer construction to allow wildcard

---

docs/components/InlineIconButton.tsx
docs/pages/guides/configuration/_meta.ts
docs/pages/guides/configuration/layout.mdx
packages/browser/src/components/filters/FilterHeader.tsx
packages/browser/src/components/library/LastVisitedLibrary.tsx
packages/browser/src/components/navigation/topbar/TopBar.tsx
packages/browser/src/components/navigation/topbar/TopBarNavLink.tsx
packages/browser/src/components/navigation/topbar/sections/UserMenu.tsx
packages/browser/src/components/navigation/topbar/sections/book-club/BookClubNavigationItem.tsx
packages/browser/src/components/navigation/topbar/sections/library/LibraryNavigationItem.tsx
packages/browser/src/components/navigation/types.ts
packages/browser/src/scenes/bookClub/tabs/settings/BookClubSettingsSideBar.tsx
packages/browser/src/scenes/library/LibraryLayout.tsx
packages/browser/src/scenes/library/LibraryNavigation.tsx
packages/browser/src/scenes/library/tabs/series/LibrarySeriesScene.tsx
packages/browser/src/scenes/library/tabs/settings/LibrarySettingsRouter.tsx
packages/browser/src/scenes/library/tabs/settings/context.ts
packages/browser/src/scenes/library/tabs/settings/options/ScannerBehaviorScene.tsx
packages/browser/src/scenes/settings/SettingsLayout.tsx
packages/browser/src/scenes/settings/SettingsSideBar.tsx
packages/browser/src/scenes/smartList/settings/SmartListSettingsSideBar.tsx
packages/client/src/queries/filesystem.ts
packages/client/src/queries/library.ts

Fixes #488
I've made small, hopefully net-positive, changes to the topbar to render the insides a bit cleaner. I did not embed a submenu inside the topbar because I hate nested menus and really want to avoid them when I can, instead I made sure there is a button for starting a scan in the library settings. I think this is enough to satisfy the linked issue imo.
As a note, I think the topbar layout is weak in UX when compared to the sidebar and eventually it would be nice to give it more love than what I had time here to do.

:lipstick: Improve small topbar nav issues

---

apps/server/src/routers/opds/v1_2.rs
core/src/db/query/pagination.rs
core/src/opds/v1_2/feed.rs
core/src/opds/v1_2/opensearch.rs

Resolves https://github.com/stumpapp/stump/issues/552
The linked issue is marked as a bug, but really this just wasn't implemented 😛 I'll leave as a draft until I resolve a quirk with Panels, I wrote a note for it in the code. For those following and interested, I posted about it in the Panels discord.

:sparkles: Support basic keyword search for OPDS v1.2

---

core/prisma/migrations/20250108021921_case_insensitive_usernames/migration.sql
packages/browser/src/scenes/settings/server/users/create-or-update/schema.ts
packages/i18n/src/locales/en.json

Fixes #556
I've adjusted the `username` column manually to add `COLLATE NOCASE` according to https://www.prisma.io/docs/orm/prisma-client/queries/case-sensitivity#sqlite-provider. I've also adjusted the frontend validation to ignore case when comparing.
I have tested manual DB insertion/updates and confirmed the migration enforces case-insensitive usernames (e.g., `oromei` or `OrOmEI` are equal). I'll try to do another validation pass tomorrow before merging, though. Edit to add that I've also tested the migration doesn't blow up my user or existing preferences, which is good I guess lol

🐛 Enforce case-insensitive username uniqueness 

---

README.md
docs/pages/guides/mobile/_meta.ts
docs/pages/guides/mobile/tachiyomi.md

Tachi seems to be deprecated, and official extensions can no longer be supported. See https://tachiyomi.org/news/2024-01-13-goodbye. If there is an alternative folks would like to see, please create a feature request

:memo: Remove Tachiyomi plans from repo and docs

---

apps/server/src/main.rs
crates/email/src/lib.rs
crates/email/src/template.rs
docs/pages/guides/basics/_meta.ts
docs/pages/guides/basics/webapp.md
docs/pages/guides/configuration/server-options.md
docs/pages/guides/desktop/index.mdx
docs/pages/guides/features/_meta.ts
docs/pages/guides/features/email.mdx

Resolves #549
I've included the default templates in the binary, something I previously forgot to do. This *should* fix the issue, but I have to do some actual verification before I am comfortable merging this in.
I also took the time over lunch to actually write some documentation for the email feature. It isn't the best, but better than it was (i.e., nothing lol)

:bug: Fix `TemplateRegistrationFailed` error when sending email

---

packages/client/src/client.ts

A user reported missing libraries in their sidebar, since it was capped at 20 I knew exactly where to look. The `usePageQuery` wrapper function I created auto adds page details to the request, but the sidebar assumes unpaginated responses. The long term fix will be to implement cursor fetching as you scroll the sidebar, but this should do for now. 
I don't have time to test right away, but I'll try to poke around and make sure this doesn't inadvertently break something else.

:bug: Remove auto-pagination for `usePageQuery` wrapper

---

apps/web/src/index.html

This enables a more seamless "Add to Home Screen" experience on iOS. See https://github.com/stumpapp/stump/issues/566#issuecomment-2610645866
I tested locally and it seems to have done the trick. The one thing to note is that it seems styling the status bar is no longer supported, e.g. `<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">`

:sparkles: Support `apple-mobile-web-app-capable` meta

---

packages/sdk/src/controllers/library-api.ts

The entire service URL was appended to the relative base URL, rather than a fully formed URL like serviceURL/relativePath

:bug: Fix incorrect URLs for library thumbnail ops

---

apps/server/src/errors.rs
apps/server/src/routers/koreader/sync.rs

This PR fixes the following error:
```
Wrong number of path arguments for `Path`. Expected 1 but got 2. Note that multiple parameters must be extracted with a tuple `Path<(_, _)>` or a struct `Path<YourParams>`
```
I just did the same fix I did when this happened for OPDS v1.2 after adding API key support to that router. The issue is that I can't force Axum to "ignore" the parent Path params for handlers of nested routers (e.g., `:document`). So when I construct a handler that only has one Path (e.g., `Path(document): Path<String>`) it rejects the request outright with that error.
Ideally, I don't need this work around but I haven't figured out how to achieve that wiht Axum yet

:bug: Fix path error in koreader router

---

core/src/filesystem/media/format/epub.rs

When doing resource lookups via the api, the path normalization for relative links (e.g. "A/../B/0.css") is broken. This fix pops up a directory when ".." is used, and removes a path component if "." is used.
The previous behavior mapped "OEBPS/../Styles/style.css" -> "OEBPS/Styles/style.css", when I think it should be "Styles/style.css".
I did try to use `std::path::absolute` since the mentioned ticket is now marked closed. However it looks like they choose to leave ".." in the path on unix systems. I did consider using it anyways, then fixing just the ".." occurrences. While feasible, I avoided it since it does resolve the whole path (e.g. "OEBPS/../Styles/style.css" -> "/home/user/stump/OEBPS/Styles/style.css". In order to fix that, the current working direct would have to be removed. …

:bug: (api) Fix path normalization for epub resource lookup

---

apps/server/src/routers/api/v1/media/mod.rs

There is an issue with serde_qs (https://docs.rs/serde_qs/latest/serde_qs/#square-brackets) with non-flattened substructs. Specifically, the way to query them is to use square brackets `metadata[writer]=Sanderson`, but this needs to be url encoded so it turns into `metadata%5Bwriter%5D=Sanderson`. In strict mode, the key gets parsed as the string `"metadata[writer]"` instead of an object and key. In non-strict mode, it will correctly parse it as nested keys.
An example would be `http://localhost:10801/api/v1/media?metadata%5Bwriter%5D=Sanderson`
Another option would be to flatten all the sub-structs. While this is possible, it seems like it might cause naming conflict issues in the future. I do not really see a valid case where the key name would have square brackets.

 🐛 (api) Fix metadata api lookup

---

packages/browser/src/components/SearchLinkBadge.tsx
packages/browser/src/scenes/book/BookOverviewScene.tsx
packages/browser/src/scenes/book/BookOverviewSceneHeader.tsx

Adds metadata into the book scene header. Each element links to a search page. I moved genres into this section but left the external links where they were.
The inspiration here came from [audibookshelf](https://audiobooks.dev/audiobookshelf/item/1551eb8a-7b16-48a7-9357-16af75d825d8) and audible. Both have a similar header section right below the titles with links to search results. The user/pass for the demo audiobookshelf is demo/demo. 
I also moved out the render header logic into a separate file. I generally try to keep files small, and this seemed link enough logic to move it out.

♻️ Rework the BookOverviewScene to include metadata information

---

crates/metadata_sources/src/lib.rs
crates/metadata_sources/src/sources/hardcover/mod.rs
crates/metadata_sources/src/sources/hardcover/request.rs
crates/metadata_sources/src/sources/hardcover/response.rs
crates/metadata_sources/src/sources/mod.rs

A proof of concept for interacting with the hardcover API for fetching book data.
Tests both title search and ISBN search.

:sparkles: Add hardcover source

---

.github/workflows/nightly.yml
Cargo.lock
Cargo.toml
apps/server/Cargo.toml
apps/server/src/routers/api/v1/filesystem.rs
apps/server/src/routers/api/v1/series.rs
core/Cargo.toml
core/src/filesystem/directory_listing.rs
core/src/filesystem/mod.rs
packages/browser/src/components/DirectoryPickerModal.tsx
packages/browser/src/components/explorer/FileExplorerProvider.tsx
packages/browser/src/components/explorer/context.ts
packages/browser/src/components/explorer/grid/FileGrid.tsx
packages/browser/src/components/explorer/table/FileTable.tsx
packages/browser/src/components/table/EntityTable.tsx
packages/browser/src/scenes/home/RecentlyAddedSeries.tsx
packages/client/src/queries/filesystem.ts
packages/sdk/src/controllers/filesystem-api.ts
packages/sdk/src/types/generated.ts

Relates to https://github.com/stumpapp/stump/issues/589
This PR should fix an issue where really large directories don't render anything in the picker modal when creating a library. I've programmatically created a folder with 100,000 (tiny) ZIP files as a test, but haven't done any real world tests. I'll try and get validation before merging this

🐛 Fix directory listing performance issues

---

packages/browser/src/components/readers/epub/EpubJsReader.tsx
packages/browser/src/components/readers/epub/EpubReaderContainer.tsx
packages/browser/src/components/readers/epub/EpubReaderFooter.tsx
packages/browser/src/components/readers/epub/context.ts
packages/browser/src/components/readers/epub/controls/ControlsContainer.tsx
packages/components/src/progress/ProgressBar.stories.tsx
packages/components/src/progress/ProgressBar.tsx

This adds support for a yomu style progress bar for epubs. The progress bar is really a list of progress bars where each bar corresponds to a section in the book.spine. Clicking on the progress bar will jump to that section of the book.
I did consider using toc instead, but things got a little messy since you have to combine sections that are not in the toc. At least a few of my books had no toc. Checking yomu, it seems to also use sections and not the toc.
I tried making it so that it jumps into the section by the same percentage of the bar the user clicked on but could not get that working reliably with epubjs. This would be useful for books that do not have chapters (e.g. convert txt files).
One significant issue here is that it has to load each section to get the text length. A better …

:sparkles: Add clickable progress bar for epubs

---

core/src/db/query/ordering.rs
core/src/filesystem/scanner/utils.rs
packages/browser/src/components/filters/form/OrderBySelect.tsx

Relatively straightforward. It looks like modified_at was not being added to the database and also not available as a sort option.
To use it, I re-created the library. I did not test if re-scanning would update modified_at.

🐛 Allow sorting media by the last time the file was modified

---

Cargo.lock
core/Cargo.toml
core/integration-tests/data/book.opf
core/src/db/entity/metadata/media_metadata.rs
core/src/filesystem/media/format/epub.rs

This is a potential solution to #593 
I am not proud of the MediaMetadata merge but it works.
This only solves the situation where the opf file has the same name as the epub.
Open to suggestions for better solutions.

:sparkles: scan matching opf file when scanning metadata for epubs

---

packages/browser/src/components/readers/epub/EpubReaderFooter.tsx

On mobile the current page and total pages in the chapter on the footer were unreliable since it didn't take into account the fact that the `start.displayed.page` and `end.displayed.page` are the same.
https://github.com/user-attachments/assets/631a0011-4f91-4645-aaec-c4286f4dbe67
https://github.com/user-attachments/assets/a4234f2c-e570-49b9-94e8-2245d4476110
I tested these changes on the `main` branch only. I'm having an issue working off of the `experimental` branch atm 😢

🐛 Fix epub reader footer page count on mobile

---

apps/web/vite.config.ts

The initial web manifest file wasn't quite working for me after it was released so I took a stab at fixing things up. The two changes here are...
* make the 'base' parameter the root app page. This parameter gets set as the 'scope' of the manifest file which determines which routes are a part of your web app. With this being set to 'assets' the browser thought none of the actual app pages were part of the PWA and rendering browser controls.
* fix the asset file name. The '.' in the previous file name was creating a file path of '/assets/./manifest.webmanifest'. this path seemed to not resolve to anything. Setting a more explicit filename here leads to the manifest link the html resolving to '/assets/manifest.webmanifest' and does actually pull up the file when that path is requested.

🩹 small improvements to web manifest PWA file

---

core/src/filesystem/media/format/pdf.rs
core/src/filesystem/scanner/utils.rs

The logs were never added to the task output, and so never got written to the database. I've also adjusted the PDF parse config to be `tolerant` during processing

:adhesive_bandage: Fix missing error logs for book failures

---

apps/server/src/routers/api/v1/library.rs
apps/server/src/routers/api/v1/media/thumbnails.rs
apps/server/src/routers/api/v1/series.rs
core/src/filesystem/error.rs
core/src/filesystem/image/error.rs
core/src/filesystem/image/generic.rs
core/src/filesystem/image/mod.rs
core/src/filesystem/image/process.rs
core/src/filesystem/image/thumbnail/generate.rs
core/src/filesystem/image/thumbnail/utils.rs
core/src/filesystem/image/webp.rs
core/src/filesystem/media/format/epub.rs
core/src/filesystem/media/format/pdf.rs
core/src/job/mod.rs

This pull request addresses several todo items in core::filesystem::image.
First, it adjusts the `ImageProcessor` trait to use `ProcessorError` as requested in a todo. In the course of doing this, I added a new `FileError::IncorrectProcessorError` variant to avoid a few `FileError::UnknownError`s. This error type could also reasonably be made a `ProcessorError` if desired, but doing it this way matched the current implementation more closely.
Second, it makes the `remove_thumbnails` function async as requested in another todo. This was done pretty easily by switching to tokio::fs. One major change I made to this function when async-ifying it was eliminating chunking and the use of the rayon crate to attempt parallel deletion across each chunk. Admittedly, I do not have a large enough test …

🩹 Switch to ProcessorError and asyncify thumbnail removal

---

packages/browser/src/components/readers/epub/EpubJsReader.tsx
packages/client/src/queries/epub.ts

when useQuery has a cache for a book entity, the first progress api request is triggered with outdated progress data.
Steps to Reproduce:
1.  Go to a book and click Continue Reading
2. Chapter one loads lets say
3. Open chapters modal and click on Chapter 2
4. Click the back arrow on the top left
5. Click Continue Reading again
6. repeat steps 2-5 and notice how the book loads alternating between chapter 1 and 2
-------
this PR removes cache from this query which is not ideal. open to suggestions! I tried using some properties that come back from useEpubLazy() but it was getting complicated same for invalidating the query cache.
Alternatively, we could prevent the very first progress api request after loading the book/entity since there should be no need for that first one. I havent …

🐛 Fix reading progress resetting due to cached data

---

apps/server/src/routers/api/v1/library.rs
apps/server/src/routers/api/v1/media/thumbnails.rs
apps/server/src/routers/api/v1/series.rs
core/src/filesystem/image/thumbnail/generate.rs
core/src/filesystem/image/thumbnail/generation_job.rs
packages/browser/src/components/entity/EntityCard.tsx
packages/browser/src/components/thumbnail/EditThumbnailDropdown.tsx
packages/browser/src/scenes/book/settings/BookThumbnailSelector.tsx
packages/browser/src/scenes/library/tabs/settings/options/thumbnails/LibraryThumbnailSelector.tsx
packages/browser/src/scenes/series/tabs/settings/SeriesThumbnailSelector.tsx
packages/sdk/src/controllers/series-api.ts

Fixes #619
The root of the issue was a regression introduced by #442, the filename was always using the book and not the actual entity (e.g., a series ID). The secondary issue of the browser cache still remains, albeit improved. After patching a thumbnail I send a `GET` to the thumbnail with cache headers aimed at busting the cache, which seems to fix the issue of having to disable the entire browser cache and refresh but still requires a refresh before you see the image.

:bug: Fix incorrect thumbnail names

---

core/src/filesystem/media/format/epub.rs

#607 Did not actually implement the feature as `process_metadata` was never called by `process`

:bug: Actually scan opf when getting metadata

---

flake.lock
flake.nix

This adds android development to the nix flake.
It works for hardware-in-loop testing. I have not tried with an emulator.

:hammer: add android dev shell to flake

---

packages/sdk/src/controllers/job-api.ts

It should have been `POST`, the SDK was sending `PUT`s

:adhesive_bandage: Fix request method for updating job scheduler

---

.github/actions/setup-rust/action.yml
Cargo.toml
apps/server/src/middleware/auth.rs
core/src/db/entity/user/entity.rs
core/src/filesystem/scanner/library_watcher.rs
core/src/opds/v2_0/group.rs
crates/codegen/Cargo.toml
crates/email/Cargo.toml
docker/Dockerfile

This PR bumps the minimum supported rust version (MSRV) to 1.85.0 and also fixes a couple of clippy lints that were added for that version.
Additionally, I went to fix a lint error by changing `UserProfile` in `core::db::entity::user` to use `Full(Box<User>)` instead and avoid bloating the size of the enum. However, I realized that the `UserProfile` isn't actually used anywhere, so I just removed it instead. Let me know if it has a future use planned and should be kept in.

⬆️ Bump MSRV

---

packages/browser/src/components/readers/epub/EpubJsReader.tsx

Finally had some time to look at this again! 
Following up on: https://github.com/stumpapp/stump/pull/615
Having both `cancelQueries` and `refetchQueries` ensures we invalidate the cache and refetch fresh data.

🐛 Fix reading progress resetting due to cached data again

---

apps/expo/app.config.ts

This PR makes it so that insecure URLs should be able to be reached on iOS

:wrench: Add `NSAllowsArbitraryLoads` to info plist

---

package.json
yarn.lock

This is in response to an exploit. See https://github.com/prettier/eslint-config-prettier/issues/339 for additional details
Note that this really only affected folks running this from source on Windows machines: https://safedep.io/eslint-config-prettier-major-npm-supply-chain-hack/#what-is-the-impact

:pushpin: Pin `eslint-config-prettier` to `9.1.2`

---

packages/browser/src/components/readers/imageBased/paged/PagedReader.tsx
packages/browser/src/scenes/book/reader/useBookPreferences.ts

This is a small fix that correctly pulls `tapSidesToNavigate` from the book-level preferences. The manifestation of the bug makes it seem like taps aren't working because the global setting was disabled.
To work around it, you just need to enable the setting globally. This is not ideal, and defeats the purpose of having book-level preferences, but is a small fix that will go out with `nightly` and whenever I can roll another version

:bug: Fix book-level `tapSidesToNavigate` not overriding global

---

packages/browser/src/components/readers/imageBased/ImageBasedReader.tsx
packages/browser/src/components/readers/imageBased/container/ControlButton.tsx
packages/browser/src/components/readers/imageBased/container/ControlsOverlay.tsx
packages/browser/src/components/readers/imageBased/container/ReaderFooter.tsx
packages/browser/src/components/readers/imageBased/container/ReaderHeader.tsx
packages/browser/src/components/readers/imageBased/container/TimerMenu.tsx
packages/browser/src/scenes/book/reader/BookReaderScene.tsx
packages/browser/src/scenes/book/reader/useBookPreferences.ts
packages/components/src/button/Button.tsx
packages/components/themes/autumn.ts
packages/components/themes/cosmic.ts
packages/components/themes/dark.ts
packages/components/themes/light.ts
packages/components/themes/ocean.ts
packages/components/themes/pumpkin.ts
packages/components/themes/types.ts

Resolves https://github.com/stumpapp/stump/issues/684
Resolves https://github.com/stumpapp/stump/issues/685
This PR fixes a few bugs all at once, but I isolated each in a separate commit. I'll likely retain each, instead of squashing, to keep a better record of what was fixed in the eventual changelog:
- The vertical scroll reader can now _actually_ scroll lol The control overlay was eating the scroll event, which prevented scroll from working
- The progress bar in the image reader foot now actually displays the percentage, not a fixed value
- I tried to improve the contrast for the buttons in the reader header for all themes, but am open to feedback if we feel they need further tweaking
- The library defaults should now be considered when resolving a book's preference bundle. The query …

🐛 Fix image reader bugs

---

crates/graphql/schema.graphql
crates/graphql/src/input/library.rs
crates/graphql/src/input/mod.rs
crates/graphql/src/input/thumbnail.rs
crates/graphql/src/mutation/library.rs
crates/graphql/src/mutation/media.rs
crates/graphql/src/mutation/series.rs
crates/graphql/src/mutation/upload.rs
database/models/src/entity/media.rs
migration.todo
packages/browser/src/scenes/book/settings/BookManagementScene.tsx
packages/browser/src/scenes/book/settings/BookThumbnailSelector.tsx
packages/browser/src/scenes/library/tabs/settings/options/thumbnails/LibraryThumbnailSelector.tsx
packages/browser/src/scenes/series/tabs/settings/SeriesSettingsScene.tsx
packages/browser/src/scenes/series/tabs/settings/SeriesThumbnailSelector.tsx
packages/graphql/src/client/gql.ts
packages/graphql/src/client/graphql.ts
packages/sdk/src/constants.ts

I still really hate the UI for the (barely implemented) book and series management pages, but I think that is a large effort for another day. This PR ports the pages to work with the new backend. I also refactored the thumbnail operations to have a bit more of a shared structure (e.g., reused input objects, functions, etc).

:construction: Migrate book management and thumbnail selectors

---

core/src/db/entity/common.rs
core/src/filesystem/scanner/library_watcher.rs
packages/browser/src/components/library/createOrUpdate/schema.ts
packages/browser/src/components/library/createOrUpdate/sections/DefaultReadingSettings.tsx
packages/browser/src/components/readers/imageBased/container/ImageScalingSelect.tsx
packages/browser/src/components/readers/imageBased/container/__tests__/ImageScalingSelect.test.tsx
packages/browser/src/components/readers/imageBased/paged/PageSet.tsx
packages/browser/src/components/readers/imageBased/paged/PagedReader.tsx
packages/client/src/stores/reader.ts
packages/sdk/src/types/generated.ts

Adds image scaling option 'auto' (always keeps page(s) within the browser window). I did not modify the scrolling reader file though. I did not set it as the default but maybe it should be. It's also in library settings so non-default is not that big of a deal.
Also fixed width scaling issue to actually use the full width when viewing pages that are low resolution.
I hope the code is okay. ~~I saw one issue where a page snapped to the left when narrowing the browser enough to go from 2 pages to 1, but I could never get it to happen again.~~ (edit: changed the code so likely doesn't apply)
There is also an issue where on ~~'auto' and~~ (edit: new code fixed this) 'width' if both pages in double page mode have different resolutions they will show up with different physical sizes, this was …

✨ Auto Scaling Option + bug fix for double paged width scaling

---

packages/browser/src/components/readers/imageBased/paged/PageSet.tsx

When changing page on Firefox and Chrome, what happens very fast is: the current pages disappear, we're left with the background, then the new ones appear. This is made worse when the page is white and the background dark. Doesn't happen on Safari unless flicking through a book really fast (which is quite slow on Safari).
Not sure I like this fix, but I didn't want to remove the keys. This makes the next set of images render with zero opacity at the required size before turning the page, meaning they are ready to use immediately on page turn. Note this is only for the forwards direction, but I can easily add the other if needed.
Outcome in my testing: 
- Firefox: only flashes if flicking through a book really fast; normal reading pace should be fine
- Chrome: zero flashing ever even if …

🐛 Fix flashing between pages

---

packages/browser/src/components/readers/epub/controls/FontSizeControl.tsx
packages/browser/src/components/readers/epub/controls/LineHeightControl.tsx
packages/browser/src/hooks/usePressAndHold.ts

Allows press and hold on mobile browsers (only tested safari)
Allows press and hold even if mouse pointer goes off the button, useful when the font preview changes size and pushes the button off the mouse pointer (still stops after mouse up)
Made buttons bigger and have hovering/pressing down indicaton. I hope I used the right `variant`, I just copied `ghost` from the other buttons.

🐛 Fix: Allow press and hold on mobile browser

---

packages/browser/src/components/readers/epub/EpubJsReader.tsx
packages/browser/src/components/readers/epub/controls/ReadingMode.tsx

Fixes scrolled mode for desktop browsers only ~and makes the useless horizontal scroll bar disappear (only for horizontal-tb books right now)~
When using a book that needs to scroll e.g. downwards, there is an annoying horizontal scroll bar because of the vertical scroll bar taking a tiny amount of space. I couldn't fix it while keeping books that scroll sideways working.
Also fixes an issue with images in books going half outside the browser window if using a tall screen.
---
One more note, I tried to change `readingDirection === 'rtl'` to `readingDirection === ReadingDirection.Rtl`, etc because of the red squigglies annoying me, but that breaks page turn direction because `'rtl'` is still the correct string to use. I'll look at it later.

🐛 Fix scrolled mode

---

packages/browser/src/components/readers/imageBased/paged/PageSet.tsx
packages/browser/src/components/readers/imageBased/paged/PagedReader.tsx

Fixes auto scaling mode for `breaking/sea-orm`
Also to me this div seems redundant? Or was it added to fix something because I just messed with it
https://github.com/stumpapp/stump/blob/2e968f91c706380352874a63134b3f0fc525ea92/packages/browser/src/components/readers/imageBased/paged/PageSet.tsx#L55-L59

🐛 fix auto scaling for image based reader

---

packages/browser/src/components/readers/epub/EpubJsReader.tsx
packages/browser/src/components/readers/epub/controls/FontSizeControl.tsx
packages/browser/src/components/readers/epub/controls/LineHeightControl.tsx
packages/browser/src/scenes/settings/app/reader/DefaultFontSize.tsx
packages/browser/src/scenes/settings/app/reader/DefaultLineHeight.tsx

So this is a weird one. There was a bug with press and hold not working on Safari on Mac only (existed before I changed anything). At first I thought I'd see what happens if I set a delay for setting `fontSize`, but near 0ms worked I guess.
Also includes a fix for arrow keys for RTL page direction books  (should of thought of that in my previous PR oops)
Edit: and now also a fix for invalid numbers being typed in as the default

🐛 Fix arrow key for ebook RTL and fix press and hold for Safari Mac

---

packages/browser/src/scenes/settings/app/general/ProfileForm.tsx

Hope this is right. I triple checked but setting `password` needs to be perfect (or else updating the avatar could remove the password).
It was an issue with the extra properties on the `user` object.

🐛 fix inability to set avatarUrl

---

packages/browser/src/components/HorizontalCardList.tsx
packages/browser/src/components/readers/epub/EpubJsReader.tsx
packages/browser/src/components/readers/epub/themes.ts
packages/browser/src/hooks/useTheme.ts
packages/browser/src/styles/index.css
packages/components/themes/autumn.ts
packages/components/themes/bronze.ts
packages/components/themes/cosmic.ts
packages/components/themes/dark.ts
packages/components/themes/light.ts
packages/components/themes/ocean.ts
packages/components/themes/pumpkin.ts
packages/components/themes/types.ts

Makes Safari and Chrome scrollbar (background) colours match the theme the same way Firefox does. I hope the implementation is okay. One annoyance is there was no setting to make it even darker when clicked and held (which Firefox does have for scrollbars and I quite like that), but it didn't work that way previously anyways.
Also a fix to make all dark themes use light text.
---
Note: Chrome does and soon Safari will support the standard [`scrollbar-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color) settings but it doesn't have colour change on hover so can't use that.

💄 Scrollbar colours for Safari and Chrome and 🐛 fix dark epubjs theme

---

packages/browser/src/scenes/library/tabs/settings/options/readingDefaults/ReadingDefaultsScene.tsx
packages/browser/src/scenes/library/tabs/settings/options/scanner/IgnoreRulesPatchForm.tsx

Fix inability to set default reader settings (i.e. Image scaling, Reading direction, Default reader)
Fix inability to set ignore rules
---
I think the typescript error in `IgnoreRulesPatchForm.tsx` is similar to the one in `ReadingDefaultsScene.tsx` so I hope it's okay.

🐛 Fix setting default reader settings

---

core/integration-tests/data/calibre-2.opf
core/src/filesystem/media/format/epub.rs
core/src/filesystem/media/metadata.rs
packages/browser/src/components/markdown/MarkdownPreview.tsx

This should fix some of the remaining issues discussed in https://github.com/stumpapp/stump/issues/658.
The root issue is that `epub-rs` is not as comprehensive as I'd like as far as the metadata it tries to pull from the embedded `.opf` file. So, I sort of added a 3 tier system:
1. Start with what `epub-rs` parsed
2. Try and fetch the embedded opf directly and parse it
3. Try and fetch an external opf and parse it
Then all 3 are merged, with external being highest priority, followed by embedded and then `epub-rs`

:bug: Fix embedded ebook metadata parsing

---

.github/actions/setup-rust/action.yml
Cargo.lock
Cargo.toml
apps/desktop/src-tauri/Cargo.toml
apps/desktop/src-tauri/src/store/secure_store.rs
apps/server/Cargo.toml
core/Cargo.toml
core/src/config/stump_config.rs
core/src/filesystem/directory_listing.rs
core/src/filesystem/hash.rs
core/src/filesystem/image/thumbnail/generation_job.rs
core/src/filesystem/media/analyze_media_job/mod.rs
core/src/filesystem/media/format/epub.rs
core/src/filesystem/scanner/library_scan_job.rs
core/src/filesystem/scanner/options.rs
core/src/filesystem/scanner/series_scan_job.rs
crates/email/Cargo.toml
crates/email/src/emailer.rs
crates/graphql/src/mutation/user.rs
crates/graphql/src/object/epub.rs
crates/models/src/shared/api_key.rs
docker/Dockerfile
rust-toolchain.toml

A little hygiene PR to upgrade most of the Rust-related dependencies in `unstable`. Most were pretty inconsequential, with a few of note:
- `epub-rs` required some changes from internal updates to some of the structs
- I removed `specta` since it isn't really needed
- Updating `async-graphql` required bumping the MSRV to `1.86.0`
- I didn't upgrade `zip` because of https://github.com/stumpapp/stump/issues/427#issuecomment-2332857700. I think Stump is _really_ starting to lag behind (current release is in the `5.x.x` range, I am using `1.1.3`). I will _try_ to slot some time to experiment with the latest to see if the issues are still present.
After this, I'll likely go through all of the Rust-related lints that remain in the `breaking/sea-orm` branch and then will promote to …

⬆️ Upgrade majority of Rust dependencies
