stumpapp/stump

- apps/server/src/middleware/auth.rs
- apps/server/src/middleware/logging.rs
- apps/server/src/routers/api/filesystem.rs
- apps/server/src/routers/api/job.rs
- apps/server/src/routers/api/library.rs
- apps/server/src/routers/api/user.rs
- common/config/package.json
- common/config/tailwind.js
- common/interface/src/components/PagePopoverForm.tsx
- common/interface/src/components/jobs/JobsTable.tsx
- common/interface/src/components/jobs/RunningJobs.tsx
- common/interface/src/components/jobs/utils.ts
- common/interface/src/components/settings/SettingsLayout.tsx
- common/interface/src/pages/settings/JobSettings.tsx
- common/interface/src/ui/Pagination.tsx
- common/interface/src/ui/table/Pagination.tsx
- common/interface/src/ui/table/Table.tsx
- core/src/event/event_manager.rs
- core/src/job/pool.rs
- pnpm-lock.yaml
Minimally functional, has a paginated table for past jobs. A little buggy, but want to get this in develop to then update main
> super basic job history table

- .github/workflows/ci.yaml
* Update GHA CI build
* Update job for current directory structure
> Update GHA CI build (#72)

- .github/actions/build-server/action.yml
- .github/actions/build-web/action.yml
- .github/actions/compile-web/action.yml
- .github/actions/pnpm-setup/action.yaml
- .github/actions/setup-system/action.yml
- .github/actions/upload-artifact/action.yml
- .github/workflows/ci.yaml
- .github/workflows/nightly.yml
- apps/desktop/package.json
- apps/desktop/src-tauri/tauri.conf.json
- apps/server/build.rs
- core/src/fs/archive.rs
This PR should provide the building blocks needed for a release pipeline. Once a day, it will pull the code, build it and upload as an artifact.
> Nightly build for web, desktop and server

- .github/actions/build-docker/action.yml
- .github/workflows/nightly.yml
Resolves https://github.com/aaronleopold/stump/issues/94
> feat(ci): add discord action

- README.md
> chore(docs): update README.md to fix broken links

- Cargo.lock
- Cargo.toml
- apps/desktop/package.json
- apps/desktop/src-tauri/Cargo.toml
- apps/server/Cargo.toml
- apps/server/src/middleware/auth.rs
- apps/server/src/routers/api/v1/log.rs
- core/Cargo.toml
- core/prisma/migrations/20231005232433_fix_series_metadata/migration.sql
- core/prisma/schema.prisma
- core/src/config/stump_config.rs
- package.json
I also went ahead and updated a lot of dependencies
> :bug: Add cascade to series metadata

- .github/actions/setup-cargo/action.yml
- .github/workflows/nightly.yml
Had to replace my machine, and there was a named reference to the previous runner. I think eventually that bit should be refactored with labels. Also removed main from the nightly CI
> :green_heart: Update runner name

- core/src/db/client.rs
There seems to be a very bad interaction that causes DB issues when setting journal_mode more than once. I have refactored the previous fix to not set on each boot
> :bug: Only set journal_mode when explicitly set

- packages/interface/src/components/sidebar/SideBar.tsx
- pnpm-lock.yaml
Fixes https://github.com/stumpapp/stump/issues/220
> :bug: Add background to aside first child in SideBar

- interface/src/components/navigation/topbar/sections/settings/SettingsNavigationItem.tsx
- interface/src/scenes/settings/SettingsHeader.tsx
- interface/src/scenes/settings/SettingsLayout.tsx
- interface/src/scenes/settings/SettingsNavigation.tsx
- interface/src/scenes/settings/SettingsRouter.tsx
- interface/src/scenes/settings/SettingsSideBar.tsx
- interface/src/scenes/settings/index.ts
- interface/src/scenes/settings/routes.ts
- interface/src/scenes/settings/server/ServerSettingsScene.tsx
- interface/src/scenes/settings/useSettingsRoutes.ts
Specifically for managed accounts without access to certain pages. Access is already blocked, so they could not access the pages, but these changes also hide the links
> :bug: Fix rendering of certain settings links

- core/src/config/stump_config.rs
- packages/types/generated.ts
Relates to https://github.com/stumpapp/stump/issues/236
Added some traces before bubbling up errors
> 🔊 Add extra logs to errors in config init

- core/src/filesystem/scanner/library_scanner.rs
Accidentally booted my server with my mounts messed up and noticed the missing series status did not go away. This PR adds the corresponding logic to set a series state back to ready once found after having been missing
> 🐛 Update previously missing when found

- core/src/opds/link.rs
- core/src/opds/opensearch.rs
Resolves #255
I verified the fix in my browser, however I'd like to try and get an emulator setup to be safe and validate moonreader (I don't have an Android device, anymore 😩)
> :bug: Fix unbound prefix in generated XML

- .github/workflows/experimental.yml
- docker/Dockerfile
I think yarn might be included in the base image now, so removed the install step. Also updated the workflow to do the same smoke build as to prevent this very kind of issue
> :adhesive_bandage: Fix dockerfile for yarn

- .github/CONTRIBUTING.md
- README.md
- apps/server/src/http_server.rs
- apps/server/src/routers/api/v1/user.rs
- core/src/config/stump_config.rs
- core/src/db/entity/user/permissions.rs
- docs/pages/guides/access-control/age-restrictions.mdx
- docs/pages/guides/basics/scanner.mdx
- docs/pages/guides/mobile/app.mdx
- docs/pages/installation/docker.mdx
- docs/pages/installation/executable.mdx
- packages/browser/src/scenes/library/management/LibraryExclusions.tsx
- packages/browser/src/scenes/library/management/LibrarySettingsScene.tsx
A few bug fixes and misc docs updates
> 0.0.2 bug hunting (round 2)

- packages/browser/package.json
- packages/components/package.json
- yarn.lock
> :arrow_down: Downgrade `react-hook-form` to `7.47.0`

- .github/CHANGELOG.md
- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- apps/desktop/package.json
- apps/desktop/src-tauri/Cargo.toml
- apps/expo/package.json
- apps/server/package.json
- apps/web/package.json
- crates/cli/Cargo.toml
- package.json
- packages/api/package.json
- packages/browser/package.json
- packages/client/package.json
- packages/components/package.json
- packages/i18n/package.json
- packages/types/package.json
- scripts/release/bump-version.sh
- 🔊 Improve logging during config init [[f1382d4](https://github.com/stumpapp/stump/commit/f1382d4bc3d015658f2d970d69aea2cad886c1be)]
- ✨ Arrangeable sidebar and topbar ([#308](https://github.com/stumpapp/stump/issues/308)) [[09b280f](https://github.com/stumpapp/stump/commit/09b280fefd4b9f7b3a862c2e0d6a141f3b92e6c5)]
- ✅ Add OPDS tests to &#x60;core&#x60; ([#301](https://github.com/stumpapp/stump/issues/301)) [[f130c8b](https://github.com/stumpapp/stump/commit/f130c8beaeb03211a2daf481576ed1bdf8d06fdf)]
- ✅ Update failing tests ([#295](https://github.com/stumpapp/stump/issues/295)) [[7b3d4d9](https://github.com/stumpapp/stump/commit/7b3d4d99fad5877f5eb1c729a56971983408ae0c)]
- ✨ Extract age rating meta for EPUB files ([#291](https://github.com/stumpapp/stump/issues/291)) …
> :bookmark: Release v0.0.2

- .github/workflows/nightly.yml
- core/src/opds/author.rs
- core/src/opds/feed.rs
- docker/Dockerfile
Relates to https://github.com/stumpapp/stump/issues/309
I've adjusted the yarn steps in the web build layer of the docker image and bumped the timeout. I'll use this PR as a testing ground until I confirm a few arm builds succeed. It will be time consuming though, since its ~3 hours on the hosted runners 😩
> 💚 Fix `yarn` timeout issues during install step

- apps/server/src/routers/api/v1/mod.rs
- packages/browser/src/components/navigation/sidebar/SideBarButtonLink.tsx
> :bug: Fix `check-for-update` false positive

- docs/pages/guides/basics/books.md
- packages/browser/src/scenes/library/management/CreateLibraryScene.tsx
- packages/browser/src/scenes/library/management/form/sections/LibraryPattern.tsx
These links are dead (404), so I made a PR to fix them.
> Fix some series/libraries-related dead links

- core/src/job/error.rs
- core/src/job/manager.rs
- core/src/job/mod.rs
- packages/browser/src/components/readers/image-based/PagedReader.tsx
I'm going to try and get a `0.0.3` out sometime soon so the version checker fix is part of a `latest` tag. This PR has a few fixes for some issues I've been able to test out so far
> Pre-0.0.3 fixes and testing

- core/src/filesystem/media/analyze_media_job.rs
A tentative fix for an issue discussed on Discord
> 🐛 Fix DB error during media analysis

- .github/workflows/ci.yaml
I used `runner` instead of `matrix` for the conditionals in the workflow file
> :construction_worker: Fix codecov upload conditions in CI

- apps/server/src/utils/auth.rs
- apps/server/src/utils/date.rs
- apps/server/src/utils/http.rs
A small PR which adds tests to a few small modules
> :white_check_mark: Add tests to improve coverage

- .github/workflows/ci.yaml
See more context here: https://discord.com/channels/972593831172272148/972595078554079232/1273071821415120959
> :construction_worker: Remote duplicate rust cache action in CI

- docs/pages/installation/getting-started.mdx
> :memo: Update docs for broken demo

- .github/actions/build-docker/action.yml
- .github/actions/setup-rust/action.yml
- .github/workflows/experimental.yml
- .github/workflows/nightly.yml
- .github/workflows/release_docker.yml
See https://github.com/stumpapp/stump/pull/424
> :construction_worker: Use `buildah` in docker CI workflows

- packages/browser/src/scenes/settings/app/appearance/ThemeSelect.tsx
- packages/components/tailwind/tailwind.js
- packages/components/themes/autumn.ts
- packages/components/themes/cosmic.ts
- packages/components/themes/index.ts
- packages/components/themes/ocean.ts
- packages/i18n/src/locales/en.json
Adds 3 themes submitted on Discord: ocean, autumn, and cosmic
> :lipstick: Add custom user-submitted themes

- docs/pages/guides/opds.md
Adds more supported clients and their issues to the OPDS tested clients section.
> 📝 Add OPDS testing reviews for Foliate, Thorium, Cantook and Librera

- docs/pages/guides/opds.md
- packages/browser/src/components/filters/FilterHeader.tsx
- packages/browser/src/scenes/library/LibraryNavigation.tsx
- packages/browser/src/scenes/library/tabs/books/LibraryBooksScene.tsx
- packages/browser/src/scenes/library/tabs/series/LibrarySeriesScene.tsx
- packages/browser/src/scenes/series/tabs/books/SeriesBooksScene.tsx
- packages/components/src/hooks/useSticky.ts
Fixes a small UI bug which affected mobile where the sticky nav was not filling with the appropriate color
> :bug: Fix transparent nav for library tabs

- apps/desktop/package.json
- apps/desktop/src/App.tsx
- packages/browser/src/scenes/auth/LoginOrClaimScene.tsx
- packages/components/src/card/Card.tsx
A really small change-set for a few misc fixes to the desktop app. The one notable aspect is that the `authMethod` is now `token` for all platforms
> 🖥️ Desktop-related cleanup and fixes

- .github/workflows/ci.yaml
- docs/package.json
A missing dependency caused build failure, I've added the dep to the app and also added another ci job to execute a build as a shallow test that nothing breaks
> :bug: Fix docs build and add CI check

- apps/server/src/routers/api/v1/user.rs
- apps/server/src/utils/test_utils.rs
- core/README.md
- core/prisma/migrations/20241226172540_job_overlay_preference/migration.sql
- core/prisma/schema.prisma
- core/src/db/entity/user/preferences.rs
- packages/browser/src/AppLayout.tsx
- packages/browser/src/scenes/settings/app/appearance/AppearanceSettingsScene.tsx
- packages/browser/src/scenes/settings/app/appearance/EnableJobOverlayToggle.tsx
- packages/sdk/src/types/generated.ts
Resolves https://github.com/stumpapp/stump/issues/531
I also forgot that the entire app appearance section is missing language translations, so I've created #541 as a follow-up task
> ✨ Allow disabling job overlay

- core/src/filesystem/scanner/utils.rs
Fixes a bad query which assumed re-build books already had metadata when performing an update. I changed this operation to an upsert to fix the error, and adjusted the relation ops
> :bug: Fix update failure for new metadata on existing books

- .github/workflows/release_binary.yml
Fixes issue reported on [Discord](https://discord.com/channels/972593831172272148/1337916835517042811)
> :pushpin: Pin `release_binary` runner to `ubuntu-22.04`

- packages/components/src/select/ComboBox.tsx
Fixes an error when a multi-select combobox is given a single-select value (i.e., not an array) from URL filters.
This could happen if you construct a URL filter that doesn't use bracket notation for fields which are multi-select.
> :bug: Fix combobox issue with malformed user-defined URL filters

- core/src/filesystem/media/format/epub.rs
The previous fallback had an issue with PathBuf usage. `starts_with` and `ends_with` only consider whole path components [link](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.starts_with), meaning `path.starts_with("cover")` would match `cover/image.png` but not `cover.png`. Similarly `path.ends_with("png")` would match `path/png` but not `path/image.png`. The second issue was that `Cover.png` would not work because the checks were case sensitive.
This change checks the lowercased version of the [file stem](https://doc.rust-lang.org/std/path/struct.Path.html#method.file_stem) for `cover` both as a prefix (cover.png) and suffix (123_cover.png).
I added a couple of other fallbacks
* Check any file for "cover" prefix or suffix (e.g. path/images/cover.png, …
> :bug: Fix fallback checks when looking for cover image

- core/src/filesystem/media/format/epub.rs
Fix an error when an epub is completely missing the cover.
> :bug: Fix scanning epub without cover

- docs/pages/guides/basics/books.md
This is a docs update to reflect the changes made in #607.
> :memo: Update docs to reflect OPF scanning for EPUBs

- docker/entrypoint.sh
Credit for that workaround to bug #646 goes to @aaronleopold, I have only successfully tested it and created this PR.
> :bug: Fix `addgroup` error for numbers beyond busybox limit

- core/src/db/filter/smart_filter.rs
- core/src/lib.rs
- crates/smart-filter-gen/src/gen_match_arms.rs
- packages/browser/src/components/smartList/createOrUpdate/schema.ts
- packages/sdk/src/types/generated.ts
Fixes https://github.com/stumpapp/stump/issues/661
This is absolutely a hack for an immediate solve. This should be revisited as part of the big migration to SeaORM to be implemented correctly, I just couldn't divert too much time to a proper fix here only to redo it later
> :bug: Fix broken tags filter for smart filters

- apps/server/src/routers/api/v1/filesystem.rs
- packages/client/src/queries/filesystem.ts
Fixes https://github.com/stumpapp/stump/issues/545
> :bug: Fix inaccessible files killing UI for directory picker

- packages/browser/src/components/readers/imageBased/ImageBasedReader.tsx
- packages/browser/src/components/readers/imageBased/container/ReaderSettings.tsx
- packages/client/src/stores/reader.ts
- packages/sdk/src/utils/__tests__/reader.test.ts
- packages/sdk/src/utils/reader.ts
Relates to the follow-up findings from https://github.com/stumpapp/stump/issues/684#issuecomment-3140953305
I haven't yet worked through all of the reported issues, but I'll leave this as draft and update the description once I have
> Fix additional image reader bugs

- packages/browser/src/components/readers/imageBased/paged/PagedReader.tsx
Fixed panzoom interfering with SideBarControl ‘active’ settings
Fixed inability to left click on SideBarControl when using image scaling ‘Width’ by observing if page set width changes. issue 2 in #679? (problem due to page set width calculation for fixSideNavigation returning wrong value after refreshing page / first time loading book into browser)
This same change also fixed the panzoom origin calculation on first time ever opening a book being wrong due to the same problem.
Fixed height of SideBarControl so that when using scaling ‘width’ on a landscape screen looking at a single portrait page it spans the whole height. (was also an issue with double pages, but it spanned nearly the full height already) It was kind of a work around, so it might not span the full height on super large …
> 🐛 Fix click to flip page (SideBarControl) issues

- apps/expo/README.md
- apps/expo/app.config.ts
- apps/expo/eas.json
- yarn.lock
Google marked this as a requirement
> :wrench: Update `targetSdkVersion` to 35 for Android

- packages/browser/src/components/library/createOrUpdate/sections/IgnoreRulesConfig.tsx
- packages/i18n/src/locales/en.json
> 🐛 Fix inability to save after removing ignore rules
